services:
#  clinic_app:
#    container_name: clinic_app
#    image: clinic/clinic_app:1.0.0
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_URL=jdbc:postgresql://clinic_db:5432/postgres
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=postgres
#    depends_on:
#      - clinic_db

  clinic_db:
    container_name: clinic_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic_database
    volumes:
      - D:\Projekty\Spring\clinic\postgresql_data:/var/lib/postgresql/data

volumes:
  pgdata: {}